class GroupPost {
  String groupId; // generated by title or subtitle
  bool userSubscribed;

  GroupPost({
    required this.groupId,
    required this.userSubscribed,
  });

  Map<dynamic, dynamic> toMap() {
    return {
      'groupId': groupId,
      'userSubscribed': userSubscribed,
    };
  }
}
